#!/bin/bash

##The PURPOSE in this repository is to practice and to track common git commands being used.

#git init				##initialize git repository 
#git add .				##move all changes to staging
#git commit -m "first commit" 		##create snapshots of staged contents
#git merge -u origin master		##merge remote branch into current branch
#git push -u origin master		##
#git restore --staged <path/file>	##
#git push -d origin <path/branch>	##delete branch locally & remotely
#git branch -d test-branch		##deletes branch locally, not remotely

#git branch -M master			##rename from main
#git push -u origin master		##push commits to remote repository
#git pull				##update the local repository with accepted pull requests!

