#!/bin/bash
###The following lines explain how to create and push code to GH repository from command line.

#git init			##initialize the git repository for development
#git add .			##move all changes to stagining
#git commit -m "first commit" 	##create snapshots of staged contents
#git merge -u origin master	##merge remote branch into current branch
#git push -u origin master		##
#git restore --staged <path/file>	##
#git push -d origin <path/branch>	##delete a branch
#git branch -d test-branch		##deletes branch locally, not remotely

##after initilizing a repository##
git remote add origin https://github.com/jgw004/Devops-Automation.git
; git branch -M main
; git push -u origin master



